# 문제 4

다음과 같은 메소드가 있을 때, 예외를 잘못 처리한 것은?
```java
void method() throws InvalidNumberException, NotANumberException {}

class NumberException extends RuntimeException {}
class InvalidNumberException extends NumberException {}
class NotANumberException extends NumberException {}
```

- a.try {method();} catch(Exception e) {}
  - O,
- b. try {method();} catch(NumberException e) {} catch(Exception e) {}
  - O
- c. try {method();} catch(Exception e) {} catch(NumberException e) {}
  - X, catch 문은 순서대로 처리하기 때문에 범위가 더 좁은 자식예외클래스가 먼저 나와야 한다.
- d. try {method();} catch(InvalidNumberException e) {
  } catch(NotANumberException e) {}
  - O,
- e. try {method();} catch(NumberException e) {}
  - O
- f. try {method();} catch(RuntimeException e) {}
  - O
