package ch8_ExceptionHandling.ex1;

public class ExceptionEx1 {
    public static void main(String[] args) {
        try {
            try {

            }
            catch (Exception e) {

            }
        } catch (Exception e) {
            /*try {

            }
            catch (Exception e) {   // 두 참조변수의 영역이 서로 겹치므로 다른 이름을 사용해야합니다.

            }*/
        }
    }
}
